auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("inactive", views.inactive, name="inactive"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("removeListing/<int:listing_id>", views.removeListing, name="removeListing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("addToWatchlist/<int:listing_id>", views.addToWatchlist, name="addToWatchlist"),
    path("removeFromWatchlist/<int:listing_id>/<str:where_to>", views.removeFromWatchlist, name="removeFromWatchlist"),
    path("categoryList", views.categoryList, name="categoryList"),
    path("categories/<str:category>", views.categories, name="categories"),
    path("listingItem/<int:listing_id>", views.listingItem, name="listingItem"),
    path("makeComment/<int:listing_id>", views.makeComment, name="makeComment"),
    path("makeBid/<int:listing_id>", views.makeBid, name="makeBid"),
    path("closeBid/<int:listing_id>", views.closeBid, name="closeBid"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models
import datetime


class User(AbstractUser):
    pass

    def __str__(self):
            return f"{self.username} [{self.email}]"

class listing(models.Model):

    CATEGORIES = [
        ('C', 'Clothing & Footwear'),
        ('H', 'Hardware and Electronics'),
        ('F', 'Furniture & Furnishings'),
        ('T', 'Toys'),
        ('D', 'Decorations'),
        ('K', 'Kitchenware'),
        ('E', 'Electrical Appliances'),
        ('O','Others'),
        ('TO', 'Toiletries')
    ]

    OPEN_OR_CLOSE = [
        ('O','Open'),
        ('C','Closed')
    ]

    name = models.CharField(max_length=64)
    desc = models.CharField(max_length=300)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listing_made")
    starting_bid = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to="listings", null=True)
    category = models.CharField(max_length=2, choices=CATEGORIES)
    watchlist = models.ManyToManyField(User, blank=True, related_name = "watchlist")
    activity = models.CharField(max_length=1, default='O', choices=OPEN_OR_CLOSE)

    def __str__(self):
        return f"{self.name} (${self.starting_bid})" 

class bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(listing, on_delete=models.CASCADE)
    bid_price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f"{self.user.username} bid {self.bid_price} on {self.listing.name})" 



class comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(listing, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} commented on {self.listing.name} [{self.date}]" 


    

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max
from .models import User, listing, bid, comment


def index(request):
    return render(request, "auctions/index.html", {'listings': listing.objects.filter(activity='O')})

def inactive(request):
    return render(request, "auctions/inactive.html", {'listings': listing.objects.filter(activity='C')})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def categoryList(request):
    return render(request, "auctions/categories.html")

def categories(request, category):
    catname = ''
    for listingItem in listing.objects.filter(category=category):
        catname = listingItem.get_category_display
        break

    return render(request, "auctions/category.html", {"listings": listing.objects.filter(category=category), 'catname':catname})

@login_required
def addToWatchlist(request, listing_id):
    current_user = User.objects.get(username=request.user.get_username())
    current_listing = listing.objects.get(pk = listing_id)
    current_listing.watchlist.add(current_user)
    return HttpResponseRedirect(reverse(listingItem, kwargs={'listing_id': listing_id}))

@login_required
def removeFromWatchlist(request, listing_id, where_to):
    current_user = User.objects.get(username=request.user.get_username())
    current_listing = listing.objects.get(pk = listing_id)
    current_listing.watchlist.remove(current_user)
    if where_to =="watchlist":
        return HttpResponseRedirect(reverse(watchlist))
    else:
        return HttpResponseRedirect(reverse(listingItem, kwargs={'listing_id': listing_id}))

    
@login_required
def watchlist(request):
    current_user = User.objects.get(username=request.user.get_username())
    return render(request, 'auctions/watchlist.html', {'watchlistItems': listing.objects.filter(watchlist=current_user)})

@login_required
def create_listing(request):
    if request.method == "POST":
        name = request.POST['name']
        desc = request.POST['desc']
        price = float(request.POST['price'])
        try:
            image = request.FILES['image']
        except:
            image = None
        category = request.POST['category']
        current_user = User.objects.get(username=request.user.get_username())
        item = listing(name = name, desc = desc, created_by = current_user, starting_bid = price, image = image, category = category)
        item.save()
        return HttpResponseRedirect(reverse(index))

    return render(request, "auctions/create.html")

@login_required
def removeListing(request, listing_id):
    current_user = User.objects.get(username=request.user.get_username())
    current_listing = listing.objects.get(pk = listing_id)
    if current_listing.created_by == User.objects.get(username=request.user.get_username()):
        current_listing.delete()
        return HttpResponseRedirect(reverse(index))

    return HttpResponseRedirect(reverse(index))


def listingItem(request, listing_id):
    current_item = listing.objects.get(id=listing_id)
    bidMax = bid.objects.filter(listing=current_item).aggregate(Max('bid_price'))
    try:
        highestBid = bid.objects.get(listing=current_item, bid_price=bidMax['bid_price__max'])

    except (NameError, ObjectDoesNotExist) as e:
        highestBid = None

    try:
        if current_item.created_by == User.objects.get(username=request.user.get_username()):
            isCreator = True
        else:
            isCreator = False

        if User.objects.get(username=request.user.get_username()) in current_item.watchlist.all():
            isWatchlisted = True
        else:
            isWatchlisted = False

        context = {
            "listing": current_item, 
            "isCreator": isCreator, 
            "isWatchlisted": isWatchlisted, 
            "comments": comment.objects.filter(listing=current_item),
            "highestBid": highestBid
        }

        return render(request, "auctions/listing.html", context)

    except (NameError, ObjectDoesNotExist) as e:
        context = {
            "listing": current_item, 
            "comments": comment.objects.filter(listing=current_item),
            "highestBid": highestBid
        }
        return render(request, "auctions/listing.html", context)

@login_required
def makeComment(request, listing_id):
    if request.method == 'POST':
        commentText = request.POST['commentText']
        current_user = User.objects.get(username=request.user.get_username())
        current_item = listing.objects.get(id=listing_id)

        commentData = comment(user=current_user, listing = current_item, comment=commentText)
        try:
            commentData.save()
        except IntegrityError:
            comment.objects.filter(user=current_user, listing=current_item).update(comment=commentText)
        return HttpResponseRedirect(reverse(listingItem, kwargs={'listing_id': listing_id}))


@login_required
def makeBid(request, listing_id):
    if request.method == 'POST':
        current_user = User.objects.get(username=request.user.get_username())
        current_item = listing.objects.get(pk=listing_id)
        bidPrice = float(request.POST['bidPrice'])

        bidMax = bid.objects.filter(listing=current_item).aggregate(Max('bid_price'))
        try:
            highestBid = bid.objects.get(listing=current_item, bid_price=bidMax['bid_price__max'])
            
            if bidPrice == current_item.starting_bid or bidPrice == highestBid.bid_price:
                bidPrice += 0.01

        except (NameError, ObjectDoesNotExist) as e:
            highestBid = None  

            if bidPrice == current_item.starting_bid:
                bidPrice += 0.01

        new_bid = bid(user = current_user, listing=current_item, bid_price=bidPrice)

        try:
            new_bid.save()
        except IntegrityError:
            bid.objects.filter(user=current_user, listing=current_item).update(bid_price=bidPrice)

        return HttpResponseRedirect(reverse(listingItem,  kwargs={'listing_id': listing_id}))

@login_required
def closeBid(request, listing_id):
    listing.objects.filter(pk=listing_id).update(activity='C')
    return HttpResponseRedirect(reverse(listingItem,  kwargs={'listing_id': listing_id}))

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block body %}

    <div class = "categories">

        <div class = "category">
            <a href="{% url 'categories' category='C' %}"><h2>Clothing and Footwear</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='H' %}"><h2>Hardware and Electronics</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='F' %}"><h2>Furniture and Furnishings</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='T' %}"><h2>Toys</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='D' %}"><h2>Decorations</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='K' %}"><h2>Kitchenware</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='E' %}"><h2>Electrical Appliances</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='TO' %}"><h2>Toiletries</h2></a>
        </div>

        <div class = "category">
            <a href="{% url 'categories' category='O' %}"><h2>Others</h2></a>
        </div>

    </div>

{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}

<h2> {{ catname }} </h2>

{% if listings %}
        {% for listing in listings %}
            <div class='listing'>
                <table>
                    <tr>
                        {% if listing.image %}
                            <td> <a href = "{% url 'listingItem' listing_id=listing.id %}"> <img src="{{ listing.image.url }}"> </a> </td>
                        {% else %}
                            <td><img src="{% static 'auctions/unnamed.jpg' %}" alt="No Image Available"></td>
                        {% endif %}
                        <td class = "details" valign="top">
                            <h3><a href="{% url 'listingItem' listing_id=listing.id %}">{{ listing.name }}</a>&nbsp;<span id="{{listing.activity}}">({{listing.get_activity_display }})</span> </h3>
                            <text> <span class="bold"> Price:</span> &nbsp;  ${{ listing.starting_bid }}</text><br>
                            <text> <span class="bold">Description:</span> &nbsp; {{ listing.desc }}</text><br>
                            <text> <span class="bold">Category:</span> &nbsp; {{ listing.get_category_display }}</text><br>
                            <text> <span class="bold">Created By:</span> &nbsp; {{listing.created_by.username}}</text><br>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}

    {% else %}

        <h4>No listings in this category</h2>

    {% endif %}

{% endblock %}

auctions/templates/auctions/create.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <form id="create_listing" action="{% url 'create_listing' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td class="label"><label>Name:</label></td>
                <td><input type="text" name="name" required></td>                
            </tr>

            <tr>
                <td class="label"><label>Description:</label></td>
                <td><textarea name="desc" required></textarea></td>
            </tr>
            
            <tr>
                <td class="label"><label>Starting Price:</label></td>
                <td><input type="text" name="price" pattern="\d+(\.\d{1,2})?" title="Must be a number with upto two decimal places." required></td> 
            </tr>

            <tr>
                <td class="label"><label>Upload Image:</label></td>
                <td><input  type="file" id="image" name="image" accept="image/*" alt="No Image Available"></td>
            </tr>

            <tr>
                <td class="label"><label>Category:</label></td>
                <td><select id="categories" name="category" required>
                    <option disabled selected value>---Select a Category---</option>
                    <option value="C">Clothing & Footwear</option>
                    <option value="H">Hardware and Electronics</option>
                    <option value="E">Electrical Appliances</option>
                    <option value="F">Furniture & Furnishings</option>
                    <option value="T">Toys</option>
                    <option value="D">Decorations</option>
                    <option value="K">Kitchenware</option>
                    <option value="TO">Toiletries</option>
                    <option value="O">Others</option>
                </select></td> 
            </tr>
        </table>

        <input id="submit" type="submit">

    </form>

{% endblock %}

auctions/templates/auctions/inactive.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}
    <h2>Inactive Listings</h2>

    {% if listings %}
        {% for listing in listings %}
            {% if listing.activity == 'C' %}
                <div class='listing'>
                    <table>
                        <tr>
                            {% if listing.image %}
                                <td> <a href = "{% url 'listingItem' listing_id=listing.id %}"> <img src="{{ listing.image.url }}"> </a> </td>
                            {% else %}
                                <td><img src="{% static 'auctions/unnamed.jpg' %}" alt="No Image Available"></td>
                            {% endif %}
                            <td class = "details" valign="top">
                                <h3><a href="{% url 'listingItem' listing_id=listing.id %}">{{ listing.name }}</a>&nbsp;<span id="{{listing.activity}}">({{listing.get_activity_display }})</span> </h3>
                                <text> <span class="bold"> Price:</span> &nbsp;  ${{ listing.starting_bid }}</text><br>
                                <text> <span class="bold">Description:</span> &nbsp; {{ listing.desc }}</text><br>
                                <text> <span class="bold">Category:</span> &nbsp; {{ listing.get_category_display }}</text><br>
                                <text> <span class="bold">Created By:</span> &nbsp; {{listing.created_by.username}}</text><br>
                            </td>
                        </tr>
                    </table>
                </div>
            {% endif %}
        {% endfor %}

    {% else %}

        <br><h4>No inactive listings</h2>
    
    {% endif %}

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}
    <h2>Active Listings</h2>

    {% if listings %}
        {% for listing in listings %}
            {% if listing.activity == 'O' %}
                <div class='listing'>
                    <table>
                        <tr>
                            {% if listing.image %}
                                <td class="itemImage"> <a href = "{% url 'listingItem' listing_id=listing.id %}"> <img src="{{ listing.image.url }}" style="margin-left:auto; margin-right:auto;"> </a> </td>
                            {% else %}
                                <td><img src="{% static 'auctions/unnamed.jpg' %}" alt="No Image Available"></td>
                            {% endif %}
                            <td class = "details" valign="top">
                                <h3><a href="{% url 'listingItem' listing_id=listing.id %}">{{ listing.name }}</a>&nbsp;<span id="{{listing.activity}}">({{listing.get_activity_display }})</span> </h3>
                                <text> <span class="bold"> Price:</span> &nbsp;  ${{ listing.starting_bid }}</text><br>
                                <text> <span class="bold">Description:</span> &nbsp; {{ listing.desc }}</text><br>
                                <text> <span class="bold">Category:</span> &nbsp; {{ listing.get_category_display }}</text><br>
                                <text> <span class="bold">Created By:</span> &nbsp; {{listing.created_by.username}}</text><br>
                            </td>
                        </tr>
                    </table>
                </div>
            {% endif %}
        {% endfor %}

    {% else %}

        <br><h4>No active listings</h2>
    
    {% endif %}

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inactive' %}">Closed Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categoryList' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% load static %}
{% load tz %}
{% block body %}

<!------------------------- Table for Listing Details --------------------------->

<div id = "listing_container">

<div id = "table_container">

<table class="listing_details">
    <tr>

<!------------------------------- Listing Image --------------------------------->

        {% if listing.image %}

            <td> <a href = "{% url 'listingItem' listing_id=listing.id %}"> <img src="{{ listing.image.url }}" style="max-height: 900px; max-width: 500px;"> </a> </td>

        {% else %}

            <td><img src="{% static 'auctions/unnamed.jpg' %}" alt="No Image Available"></td>

        {% endif %}

<!------------------------------ Listing Details ---------------------------------->

        <td class = "details" valign="top">
            <h3>{{ listing.name }}&nbsp;<span id="{{listing.activity}}">({{listing.get_activity_display }})</span> </h3>

            {% if user.is_authenticated %}

                {% if isWatchlisted %}

                    <text class="remove"><a href="{% url 'removeFromWatchlist' listing_id=listing.id where_to='listingItem'%}">Remove from Watchlist</a></text><br>

                {% else %}

                    <text><a href="{% url 'addToWatchlist' listing_id=listing.id %}">Add to Watchlist</a></text><br>

                {% endif %}

            {% endif %}

            <text> <span class="bold">Starting Price:</span> &nbsp; ${{ listing.starting_bid }}</text><br>
            {% if highestBid %}
                <text> <span class="bold">Current Price:</span> &nbsp; ${{highestBid.bid_price}}</text><br>
            {% endif %}
            <text> <span class="bold">Description:</span> &nbsp; {{ listing.desc }}</text><br>
            <text> <span class="bold">Category:</span> &nbsp; {{ listing.get_category_display }}</text><br>
            <text> <span class="bold">Created By:</span> &nbsp; {{listing.created_by.username}}</text><br>
            {% if highestBid %}
                <text> <span class="bold">Highest Bidder:</span> &nbsp; {{highestBid.user.username}}</text><br>
            {% endif %}

<!-------------------------------Make/Close Bid Form--------------------------------->

            {% if listing.activity == 'O' %}    

                {% if not isCreator %}

                    <form id="bidding" action="{% url 'makeBid' listing_id=listing.id%}" method="POST">
                        {% csrf_token %}

                        <span class="bold"><label>Make a bid:</label></span>

                        {% if listing.starting_bid < highestBid.bid_price %}

                            <input name="bidPrice" type="number" min="{{ highestBid.bid_price }}" max="9999" step=".01" required><br>

                        {% else %}

                            <input name="bidPrice" type="number" min="{{ listing.starting_bid }}" max="9999" step=".01" required><br>

                        {% endif %}

                        <input class="bidSubmit" type="submit">
                    </form>

                {% else %}

                    <text><a href = "{% url 'closeBid' listing_id=listing.id %}">Close this Bid</a></text><br>

                {% endif %}

            {% else %}

                {% if user.username == highestBid.user.username %}

                <br><text><h4 id="win">You have won the bid!</h4></text>

                {% endif %}

            {% endif %}

<!------------------------------- Remove Listing Link --------------------------------->

            {% if user.is_authenticated %}

                {% if isCreator %}

                    <br><br><br><br><br><br><text class="remove"><a href="{% url 'removeListing' listing_id=listing.id %}">Delete Listing</a></text>

                {% endif %}

            {% endif %}

        </td>
    </tr>
</table>

<!---------------------------------- Comment Form ------------------------------------>

{% if user.is_authenticated %}

<form id="comment_form" action="{% url 'makeComment' listing_id=listing.id%}" method="POST">
    {% csrf_token %}
    <h3>Write a Comment:</h3>
    <textarea name="commentText" wrap="hard" cols="120" rows="5" required></textarea><br>
    <input type="submit">
</form>

{% endif %}

</div>

<!--------------------------------- List of Comments --------------------------------->

<div id = "comments_container">

<h2>Comments:</h2>

{% if comments %}

{% for comment in comments %}

    <div class="comments">
        <div id="user_details">
            <h5>{{ comment.user.username }}</h5> 
            <time>{{ comment.date|localtime }}</time><br>
        </div>
        <div id="content">

            <p>{{comment.comment}}</p>

        </div>
    </div>

{% endfor %}

{% else %}

<text>No Comments Yet</text>

{% endif %}

</div>

</div>

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% load static %}

{% block body %}

    {% if watchlistItems %}
        {% for listing in watchlistItems %}
            <div class='listing'>
                <table>
                    <tr>
                        {% if listing.image %}
                            <td> <a href = "{% url 'listingItem' listing_id=listing.id %}"> <img src="{{ listing.image.url }}"> </a> </td>
                        {% else %}
                            <td><img src="{% static 'auctions/unnamed.jpg' %}" alt="No Image Available"></td>
                        {% endif %}
                        <td class = "details" valign="top">
                            <h3><a href="{% url 'listingItem' listing_id=listing.id %}">{{ listing.name }}</a>&nbsp;<span id="{{listing.activity}}">({{listing.get_activity_display }})</span> </h3>
                            <text> <span class="bold"> Price:</span> &nbsp;  ${{ listing.starting_bid }}</text><br>
                            <text> <span class="bold">Description:</span> &nbsp; {{ listing.desc }}</text><br>
                            <text> <span class="bold">Created By:</span> &nbsp; {{listing.created_by.username}}</text><br>
                            <text class="remove"><a href="{% url 'removeFromWatchlist' listing_id=listing.id  where_to='watchlist' %}">Remove from Watchlist</a></text>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}

    {% else %}
    <h4>Nothing in watchlist</h2>

    {% endif %}

{% endblock %}